name: Master
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure Docker credentials
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.DOCKER_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Checkout code
          id: checkout
          uses: actions/checkout@v1
      - name: Build, tag, and push image to Azure Container Registry
          id: build-image
          run: |
            docker build . -t ${{ secrets.DOCKER_URL }}/pyazuredemo1:${{ github.sha }}
            docker push ${{ secrets.DOCKER_URL }}/pyazuredemo1:${{ github.sha }}

